### ISSUE TITLE
Impossible to launch one of the demos projects

### ISSUE THREAD

**Issue by energy-haken** [easy-model-fusion/demos#14]
![image_2024-09-13_154855129](https://github.com/user-attachments/assets/276e40cb-b46c-4a9b-af87-6edf6fbaa7cc)

I could install and build the project (the "source .venv/bin/activate" command didn't work) but when i launch the exe file i had this error code , even when launchin in administrator mode

**Comment by SchawnnDev** [comment]
Hello, thanks for your interest in the project!

`source .venv/bin/activate` is for linux!
Since you use windows with powershell, use this command instead: `.\.venv\Scripts\activate.ps1`

To answer to the problem on the screen you sent:

This demo has this [option](https://github.com/easy-model-fusion/demos/blob/a906f45c7d616666b4fbb14b1751cb6d04ef30c1/text-to-image-gui/config.yaml#L16C1-L16C25 ) checked `isdownloaded: true`, that means that the executable will not download the model files on launch and that you need to have them in the same folder as the executable (adding model files to an executable would be a stupid idea, as the executable would be far too large). So copy the executable to the `model-prompt-to-image-gui/` folder or copy the models folder to the `dist/` folder.

I'm available for any questions if needed.

**Comment by energy-haken** [comment]
Thank you very much ! Now i still have an error but not the same... 
![image](https://github.com/user-attachments/assets/49039aa1-5632-4fd4-a678-d02c761d7bff)

**Comment by SchawnnDev** [comment]
Make sure you used --cuda : https://easy-model-fusion.github.io/docs/basics.html#installing-an-existing-project

**Comment by energy-haken** [comment]
Hi , sorry again , does all the models use CUDA ? Because it looks like without an NVIDIA graphic card it doesnt work.

**Comment by SchawnnDev** [comment]
The model we using in this demo is not really suited to be processed by a cpu, but you can try it this way:

Add `self.img_model.device = sdk.Devices.CPU` after `self.img_model = sdk.StabilityaiStableDiffusionXlBase10(**self.img_model_options)` and also remove the options `**self.img_model_options` so that it finally looks like this:
```
self.img_model = sdk.StabilityaiStableDiffusionXlBase10()
self.img_model.device = sdk.Devices.CPU
```
 [here](https://github.com/easy-model-fusion/demos/blob/a906f45c7d616666b4fbb14b1751cb6d04ef30c1/model-prompt-to-image-gui/main.py#L37C9-L37C90)

And the same for all models you use (in this case the two models)
